name: build

on: [push]

jobs:
  build:
    name: Build on python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.9]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Configure poetry
        run: poetry config virtualenvs.in-project true
      - name: Install Dependencies
        run: poetry install
      - name: Lint
        run: poetry run inv lint
      - name: Test
        run: poetry run inv test
      - name: Build
        run: poetry build
